#include "DrvADC_Private.h"

    (TS_DrvADC_Registers *) DRVADC_ADC1_ADDRESS }; const TS_DrvADC_Port_Definition C_DrvADC_Port_Def [DRVADC_ANALOG_MAX_NB] = {    {DRVADC_ADC0_ID, DRVADC_SC1A_CAM_HS_CURRENT, DRVADC_CAM_HS_CURRENT_GAIN, 0.0f},    {DRVADC_ADC0_ID, DRVADC_SC1A_CAM_LS_CURRENT, DRVADC_CAM_LS_CURRENT_GAIN, 0.0f},    {DRVADC_ADC0_ID, DRVADC_SC1A_CAM_VLOAD,      DRVADC_CAM_VLOAD_GAIN,      0.0f},    {DRVADC_ADC1_ID, DRVADC_SC1A_TEMPERATURE,    DRVADC_TEMPERATURE_GAIN,    DRVADC_TEMPERATURE_OFFSET}
