LIB_NAME := LIBBSP_MATH
SCI := LIBBSP
SOURCES_FILES:=\
LIBBSP_MATH_Casts.c\
LIBBSP_MATH_BZero.c\
LIBBSP_MATH_Globals.c

SOURCES_FILES_S:=\
LIBBSP_MATH_LogShift64.s

INCLUDE_FILES := ../../LIBBSP_api/LIBBSP_MATH ../../LIBMCP_api

include ../../Makefile/MakefileLib.mk




