# ----------------------------------------------------------------------------------------------------------------------
#                                             SAFRAN Electronics & Defense
#                                        Reproduction and disclosure forbidden.
# ----------------------------------------------------------------------------------------------------------------------
# DESCRIPTION : Makefile for error_handler directory
# ----------------------------------------------------------------------------------------------------------------------

include R:/_build_proc/mak/conf_psyko.mak

include conf_error_handler.mak

include make_error_handler.mak
