#ifndef _BOOT_CONSTS_
#define _BOOT_CONSTS_

#include "LIBUTI_BOOT.h"

#define C_BOOT_MAX_NUMBER_OF_DATA_FILES         50ul
#define C_BOOT_MAX_NUMBER_OF_SUPPORT_FILES      10ul
#define C_BOOT_MAX_NUMBER_OF_FILES              (uint32_t)(C_BOOT_MAX_NUMBER_OF_DATA_FILES + C_BOOT_MAX_NUMBER_OF_SUPPORT_FILES + 1ul)  /*+1 for the LUH*/
#define C_BOOT_MAX_NUMBER_OF_COMPAT_RULES       (uint32_t)(C_MAX_BOOT_DESCRIPTOR_NUMBER_OF_COMPAT_CRIT)
#define C_BOOT_MAX_NUMBER_OF_TARGET_HW_IDS      10ul
#define C_BOOT_LOAD_NAME_MAX_LENGTH             (uint32_t)(C_LOAD_NAME_MAX_LENGTH)
#define C_BOOT_MAX_NUMBER_OF_SECONDARY_LOAD     (uint32_t)(C_MAX_NUMBER_OF_SECONDARY_LOAD)
#define C_BOOT_PN_LENGTH                        (uint32_t)(C_LOAD_PN_LENGTH)

#define C_BOOT_LUH_MIN_LENGTH                   10ull
#define C_BOOT_LUH_MAX_LENGTH                   25374ull
#define C_BOOT_SIF_HEADER_MAX_LENGTH            0x2000ul
#define C_BOOT_CMP_MAX_LENGTH                   (uint32_t)(104ul + (C_BOOT_MAX_NUMBER_OF_COMPAT_RULES * 72ul))
#define C_BOOT_SUP_MAX_LENGTH                   (uint32_t)(6ul + (C_BOOT_MAX_NUMBER_OF_DATA_FILES * 74ul))
#define C_BOOT_LUD_MAX_LENGTH                   (uint32_t)(8ul + (C_BOOT_MAX_NUMBER_OF_SECONDARY_LOAD * 72ul))
#define C_BOOT_FLASH_INTEGRITY_LUP_BUFFER_SIZE  0x4000ul

#define C_BOOT_MRAM_AESKEY_ZONE_OFFSET          0x00040000ul

#define C_BOOT_PLD_SHM_BASE_ADDRESS             0xF2000000ul
#define C_BOOT_PLD_WATCHDOG_BASE_ADDRESS        (C_BOOT_PLD_SHM_BASE_ADDRESS + 0x2000ul)
#define C_BOOT_PLD_GLOBAL_REGS_BASE_ADDRESS     (C_BOOT_PLD_SHM_BASE_ADDRESS + 0x3000ul)

#define C_BOOT_LUH_EXT_LENGTH                   4ul
#define C_BOOT_LUH_EXT                          ".LUH"


#define C_BOOT_PLD_ENVM_ADDR_DTL_START          0x00010C00ul
#define C_BOOT_PLD_ENVM_ADDR_DTL_END            0x00010E80ul
#define C_BOOT_PLD_ENVM_ADDR_AES_START          0x00014080ul
#define C_BOOT_PLD_ENVM_ADDR_AES_END            0x00014100ul
#define C_BOOT_PLD_ENVM_ADDR_OPR_START          0x0001EF00ul
#define C_BOOT_PLD_ENVM_ADDR_OPR_END            0x00021680ul

#define C_BOOT_RMM_ADDR_SIF_START               0x00018000ul
#define C_BOOT_RMM_ADDR_SHA_START               0x0001E000ul
#define C_BOOT_RMM_ADDR_AES_START               0x0001F000ul

#define C_BOOT_AES_KEY_MAX_LENGTH               (C_BOOT_PLD_ENVM_ADDR_AES_END - C_BOOT_PLD_ENVM_ADDR_AES_START)

#define C_PLD_COMPAGNON_FAIL_SWITCH_GOLDEN      0x7E162366ul
#define C_PLD_COMPAGNON_DSO_SYSFAIL_GOLDEN      0xCF97B7EAul
#define C_PLD_COMPAGNON_PBITOK_SWITCH_GOLDEN    0x04BDA16Ful
#define C_PLD_COMPAGNON_WATCHDOG_REARM_GOLDEN   0x22BD4C96ul

#endif